# Ref: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml

# Default values for prometheus-node-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  registry: quay.io
  repository: prometheus/node-exporter
  # Overrides the image tag whose default is {{ printf "v%s" .Chart.AppVersion }}
  tag: ""
  pullPolicy: IfNotPresent
  digest: ""

fullnameOverride: "node-exporter"

# Number of old history to retain to allow rollback
# Default Kubernetes value is set to 10
revisionHistoryLimit: 2


## Service configuration
service:
  ## Creating a service is enabled by default
  enabled: true

  ## Service type
  type: ClusterIP
  ## IP address for type ClusterIP
  clusterIP: ""
  ## Default service port. Sets the port of the exposed container as well (NE or kubeRBACProxy).
  ## Use "servicePort" below if changing the service port only is desired.
  port: 9100

  ## Targeted port in the pod. Must refer to an open container port ("port" or "portName").
  ## (IntOrString)
  targetPort: 9100
  ## Name of the service port. Sets the port name of the main container (NE) as well.
  portName: metrics

  ## Additional annotations and labels for the service
  annotations:
    prometheus.io/scrape: "true"


# Set a NetworkPolicy with:
# ingress only on service.port or custom policy
# no egress permitted
networkPolicy:
  enabled: false


prometheus:
  monitor:
    enabled: true

## Customize the updateStrategy if set
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1

resources:
  limits:
    cpu: 200m
    memory: 50Mi
  requests:
    cpu: 100m
    memory: 30Mi


serviceAccount:
  create: true

securityContext:
  fsGroup: 65534
  runAsGroup: 65534
  runAsNonRoot: true
  runAsUser: 65534

containerSecurityContext:
  readOnlyRootFilesystem: true
  # capabilities:
  #   add:
  #   - SYS_TIME

rbac:
  ## If true, create & use RBAC resources
  ##
  create: true


## Extra labels to attach to all resources (can be templated)
commonLabels:
  app: node-exporter
  stack: monitoring


## Assign a nodeSelector if operating a hybrid cluster
##
nodeSelector:
  tier: monitoring
  #  kubernetes.io/arch: amd64

tolerations:
  - effect: NoSchedule
    operator: Exists

## Additional InitContainer to fix hostfile permissions required for some exporters. All fixes are disabled by default.
##
permissionInitContainer:
  image:
    registry: quay.io
    repository: prometheus/busybox
    tag: latest
    sha: ""
    pullPolicy: IfNotPresent
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false
  fixes:
    # Fixes /sys/devices/virtual/powercap/*/energy_uj
    # Collector enabled by default
    rapl: false
    # Fixes /proc/slabinfo
    # Collector disabled by default
    slabinfo: false
  extraCommands: []

## Liveness probe
##
livenessProbe:
  failureThreshold: 3
  httpGet:
    httpHeaders: []
    scheme: http
  initialDelaySeconds: 0
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

## Readiness probe
##
readinessProbe:
  failureThreshold: 3
  httpGet:
    httpHeaders: []
    scheme: http
  initialDelaySeconds: 0
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
