apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: logging

  sources:
    - repoURL: https://github.com/ViniciusPilan/metrics-setup-of-dreams.git
      targetRevision: v1
      ref: values

    # Loki
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: grafana/loki
      targetRevision: 6.41.0
      helm:
        # releaseName: grafana
        valueFiles:
          - $values/cluster-tools/logging/loki/values.yaml


  syncPolicy:
    syncOptions:
      - CreateNamespace=true
