apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-tools
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: metrics

  sources:
    - repoURL: https://github.com/ViniciusPilan/metrics-setup-of-dreams.git
      targetRevision: v1
      ref: values

    # Prometheus
    - repoURL: ghcr.io/prometheus-community/charts
      chart: kube-prometheus-stack
      targetRevision: 83.6.0
      helm:
        valueFiles:
          - $values/cluster-tools/metrics/prometheus/base.yaml
          - $values/cluster-tools/metrics/prometheus/values.yaml

    # Prometheus Operator
    - repoURL: ghcr.io/prometheus-community/charts
      chart: kube-prometheus-stack
      targetRevision: 83.6.0
      helm:
        # releaseName: prometheus
        valueFiles:
          - $values/cluster-tools/metrics/prometheus-operator/base.yaml
          - $values/cluster-tools/metrics/prometheus-operator/values.yaml

    # Kube state metrics

    # Grafana Alloy

    # Alertmanager

    # Node Exporter

    # Push Gateway

    # BlackBox Exporter


  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
