apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: metrics

  sources:
    - repoURL: https://github.com/ViniciusPilan/metrics-setup-of-dreams.git
      targetRevision: v1
      ref: values
    
    # Mimir
    # - repoURL: https://grafana.github.io/helm-charts
    #   chart: mimir-distributed
    #   targetRevision: 6.0.6
    #   helm:
    #     valueFiles:
    #       - $values/cluster-tools/metrics/mimir/values.yaml

    # Etcd
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: etcd
      targetRevision: 12.0.18
      helm:
        valueFiles:
          - $values/cluster-tools/metrics/mimir/etcd/values.yaml

    # Kakfa

  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
