apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-tools
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  sources:
    - repoURL: https://github.com/ViniciusPilan/metrics-setup-of-dreams.git
      targetRevision: v0
      ref: values

    # Prometheus Operator
    - repoURL: ghcr.io/prometheus-community/charts
      chart: kube-prometheus-stack
      targetRevision: 83.6.0
      helm:
        valueFiles:
          - $values/cluster-tools/monitoring/prometheus-operator/values.yaml

    # # Prometheus
    # - repoURL: ghcr.io/prometheus-community/charts
    #   chart: kube-prometheus-stack
    #   targetRevision: 83.6.0
    #   helm:
    #     valueFiles:
    #       - $values/cluster-tools/monitoring/prometheus/values.yaml

    # # Kube state metrics
    # - repoURL: ghcr.io/prometheus-community/charts
    #   chart: kube-state-metrics
    #   targetRevision: 7.2.2
    #   helm:
    #     valueFiles:
    #       - $values/cluster-tools/monitoring/kube-state-metrics/values.yaml 

    # # Node exporter
    # - repoURL: ghcr.io/prometheus-community/charts
    #   chart: prometheus-node-exporter
    #   targetRevision: 4.53.1
    #   helm:
    #     valueFiles:
    #       - $values/cluster-tools/monitoring/node-exporter/values.yaml

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
