# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: popeye
#   namespace: argocd
# spec:
#   project: default

#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: cluster-general-tools

#   sources:
#     - repoURL: https://github.com/ViniciusPilan/metrics-setup-of-dreams.git
#       targetRevision: v1
#       path: cluster-tools/general/popeye
