# https://github.com/derailed/popeye#in-cluster
apiVersion: batch/v1
kind: CronJob
metadata:
  name: popeye
spec:
  schedule: "* * */30 * *" # Fire off Popeye once an hour
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: popeye
          restartPolicy: Never
          containers:
            - name: popeye
              image: derailed/popeye:v0.22.1
              imagePullPolicy: IfNotPresent
              args:
                - -o
                - yaml
                - --force-exit-zero
                - --push-gtwy-url
                - http://push-gateway.metrics.svc:9090
              resources:
                limits:
                  cpu:    500m
                  memory: 100Mi
