apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  sources:
    - repoURL: https://github.com/ViniciusPilan/metrics-setup-of-dreams.git
      targetRevision: v1
      ref: values

    # Grafana
    - repoURL: ghcr.io/grafana-community/helm-charts
      chart: grafana
      targetRevision: 12.1.1
      helm:
        releaseName: grafana
        valueFiles:
          - $values/cluster-tools/monitoring/grafana/values.yaml

  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
